[package]
name = "http_auth_digest_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest_auth = "0.3.0"
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
http = "0.2"